### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by justin-echternach** [wonglok/enstudio#1]
What has to be done to get this working on windows?  I'll do the coding ...

**Comment by wonglok** [comment]
hi :D thanks for liking my software <3 
![image](https://user-images.githubusercontent.com/4082826/109708948-fc3ce880-7bd6-11eb-91da-d40e5c6e973d.png)

You can add win32 or win64 to the nwBuilder -> platforms array in package.json

**Comment by justin-echternach** [comment]
That's it.  Awesome.  Thanks a ton.  Your tool looks great!

**Comment by justin-echternach** [comment]
get this when running yarn dev.  I have all the node_modules

Starting the development server...

C:\_dev\repos\enstudio\node_modules\glob\sync.js:341
        throw er
        ^

Error: EPERM: operation not permitted, scandir 'C:/_dev/repos/enstudio/build/enstudio/osx64/enstudio.app/Contents/Frameworks/nwjs Framework.framework/Helpers'
    at Object.readdirSync (fs.js:1021:3)
    at GlobSync._readdir (C:\_dev\repos\enstudio\node_modules\glob\sync.js:288:41)
    at GlobSync._readdirInGlobStar (C:\_dev\repos\enstudio\node_modules\glob\sync.js:267:20)     
    at GlobSync._readdir (C:\_dev\repos\enstudio\node_modules\glob\sync.js:276:17)
    at GlobSync._processGlobStar (C:\_dev\repos\enstudio\node_modules\glob\sync.js:350:22)       
    at GlobSync._process (C:\_dev\repos\enstudio\node_modules\glob\sync.js:130:10)
    at GlobSync._processGlobStar (C:\_dev\repos\enstudio\node_modules\glob\sync.js:383:10)       
    at GlobSync._process (C:\_dev\repos\enstudio\node_modules\glob\sync.js:130:10)
    at GlobSync._processGlobStar (C:\_dev\repos\enstudio\node_modules\glob\sync.js:383:10)       
    at GlobSync._process (C:\_dev\repos\enstudio\node_modules\glob\sync.js:130:10) {
  errno: -4048,
  syscall: 'scandir',
  code: 'EPERM',
  path: 'C:/_dev/repos/enstudio/build/enstudio/osx64/enstudio.app/Contents/Frameworks/nwjs Framework.framework/Helpers'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by justin-echternach** [comment]
Nevermind ... I got it.   Changed the platform to win64

**Comment by justin-echternach** [comment]
I changed it under the nw_builder part of the config ... fyi.

**Comment by wonglok** [comment]
Hi, let's run the command with admin rights in Windows? I saw the Permission error code name

**Comment by wonglok** [comment]
Or maybe I build a windows version

**Comment by wonglok** [comment]
https://github.com/wonglok/enstudio/releases/tag/r005

@justin-echternach please give the latest build a try, it has windows build :) hope it works on windows
